using RimWorld;

namespace Intercolony
{
    /// <summary>
    /// Defs Intercolony ships and needs by name.
    ///
    /// <see cref="Intercolony_Employment"/> is the marker script for employment quests. It is
    /// never generated by the storyteller (its def sets <c>randomlySelectable false</c>); it
    /// exists so employment quests have a non-null <c>root</c>, without which
    /// <c>Quest.CleanupQuestParts</c> throws on every dismissal.
    /// </summary>
    [DefOf]
    public static class IntercolonyQuestDefOf
    {
        public static QuestScriptDef Intercolony_Employment;

        static IntercolonyQuestDefOf()
        {
            DefOfHelper.EnsureInitializedInCtor(typeof(IntercolonyQuestDefOf));
        }
    }
}
